name: check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install


      - name: Run linter
        run:
          make lint
          
      - name:
        run:
          make pytest

      - name: Setup Code Climate
        uses: remarkablemark/setup-codeclimate@v2
  
      - name: Download Code Climate test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      
      - name: Run Tests and Upload Coverage
        run: |
          ./cc-test-reporter before-build
          poetry run pytest --cov=gendiff --cov-report=lcov
          ./cc-test-reporter after-build --exit-code $? --coverage-input-type lcov  --file coverage.lcov
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}