name: chek

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          
      - name: Run linter and pytest
        run: |
          make lint
          poetry run pytest

      
        
